variables:
  PROJECT: my-project
  RUNNER: dev
  AGENT: dakual/gitlab-ci-downstream:dev 

stages:
  - build
  - deploy

chart-builder:
  stage: build
  image: alpine:3.17
  script:
    - chmod +x build-pipeline.sh
    - sh build-pipeline.sh > build-pipeline.yml
  artifacts:
    expire_in: 1 hour
    paths:
      - build-pipeline.yml
  rules:
    - if: '$CI_COMMIT_TAG =~ "/^$/"'
      changes:
      - charts/**/*
  tags: 
    - ${RUNNER}

chart-jobs:
  stage: build
  needs:
    - chart-builder
  trigger:
    include:
      - artifact: build-pipeline.yml
        job: chart-builder
    strategy: depend
  rules:
    - if: '$CI_COMMIT_TAG =~ "/^$/"'
      changes:
      - charts/**/*